import Face3OutlinedIcon from "@mui/icons-material/Face3Outlined";
import NightlifeOutlinedIcon from "@mui/icons-material/NightlifeOutlined";
import KingBedOutlinedIcon from "@mui/icons-material/KingBedOutlined";
import HouseOutlinedIcon from "@mui/icons-material/HouseOutlined";
import CountertopsOutlinedIcon from "@mui/icons-material/CountertopsOutlined";

export const CATEGORIES = [
  {
    slug: "beauty",
    name: "Beauty",
    url: "https://dummyjson.com/products/category/beauty",
    icon: Face3OutlinedIcon,
    bg: "bg-pink-500",
    color: "text-white",
  },
  {
    slug: "fragrances",
    name: "Fragrances",
    url: "https://dummyjson.com/products/category/fragrances",
    icon: NightlifeOutlinedIcon,
    bg: "bg-blue-500",
    color: "text-white",
  },
  {
    slug: "furniture",
    name: "Furniture",
    url: "https://dummyjson.com/products/category/furniture",
    icon: KingBedOutlinedIcon,
    bg: "bg-green-500",
    color: "text-white",
  },
  {
    slug: "groceries",
    name: "Groceries",
    url: "https://dummyjson.com/products/category/groceries",
    icon: NightlifeOutlinedIcon,
    bg: "bg-yellow-500",
    color: "text-black",
  },
  {
    slug: "home-decoration",
    name: "Home Decoration",
    url: "https://dummyjson.com/products/category/home-decoration",
    icon: HouseOutlinedIcon,
    bg: "bg-red-500",
    color: "text-white",
  },
  {
    slug: "kitchen-accessories",
    name: "Kitchen Accessories",
    url: "https://dummyjson.com/products/category/kitchen-accessories",
    icon: CountertopsOutlinedIcon,
    bg: "bg-purple-500",
    color: "text-white",
  },
  {
    slug: "laptops",
    name: "Laptops",
    url: "https://dummyjson.com/products/category/laptops",
    icon: NightlifeOutlinedIcon,
    bg: "bg-gray-500",
    color: "text-white",
  },
  {
    slug: "mens-shirts",
    name: "Mens Shirts",
    url: "https://dummyjson.com/products/category/mens-shirts",
    icon: NightlifeOutlinedIcon,
    bg: "bg-blue-700",
    color: "text-white",
  },
  {
    slug: "mens-shoes",
    name: "Mens Shoes",
    url: "https://dummyjson.com/products/category/mens-shoes",
    icon: NightlifeOutlinedIcon,
    bg: "bg-amber-950",
    color: "text-white",
  },
  {
    slug: "mens-watches",
    name: "Mens Watches",
    url: "https://dummyjson.com/products/category/mens-watches",
    icon: NightlifeOutlinedIcon,
    bg: "bg-black",
    color: "text-white",
  },
  {
    slug: "mobile-accessories",
    name: "Mobile Accessories",
    url: "https://dummyjson.com/products/category/mobile-accessories",
    icon: NightlifeOutlinedIcon,
    bg: "bg-blue-900",
    color: "text-black",
  },
  {
    slug: "motorcycle",
    name: "Motorcycle",
    url: "https://dummyjson.com/products/category/motorcycle",
    icon: NightlifeOutlinedIcon,
    bg: "bg-red-700",
    color: "text-white",
  },
  {
    slug: "skin-care",
    name: "Skin Care",
    url: "https://dummyjson.com/products/category/skin-care",
    icon: NightlifeOutlinedIcon,
    bg: "bg-pink-600",
    color: "text-black",
  },
  {
    slug: "smartphones",
    name: "Smartphones",
    url: "https://dummyjson.com/products/category/smartphones",
    icon: NightlifeOutlinedIcon,
    bg: "bg-purple-700",
    color: "text-white",
  },
  {
    slug: "sports-accessories",
    name: "Sports Accessories",
    url: "https://dummyjson.com/products/category/sports-accessories",
    icon: NightlifeOutlinedIcon,
    bg: "bg-green-800",
    color: "text-black",
  },
  {
    slug: "sunglasses",
    name: "Sunglasses",
    url: "https://dummyjson.com/products/category/sunglasses",
    icon: NightlifeOutlinedIcon,
    bg: "bg-yellow-900",
    color: "text-black",
  },
  {
    slug: "tablets",
    name: "Tablets",
    url: "https://dummyjson.com/products/category/tablets",
    icon: NightlifeOutlinedIcon,
    bg: "bg-gray-600",
    color: "text-black",
  },
  {
    slug: "tops",
    name: "Tops",
    url: "https://dummyjson.com/products/category/tops",
    icon: NightlifeOutlinedIcon,
    bg: "bg-blue-500",
    color: "text-white",
  },
  {
    slug: "vehicle",
    name: "Vehicle",
    url: "https://dummyjson.com/products/category/vehicle",
    icon: NightlifeOutlinedIcon,
    bg: "bg-red-600",
    color: "text-black",
  },
  {
    slug: "womens-bags",
    name: "Womens Bags",
    url: "https://dummyjson.com/products/category/womens-bags",
    icon: NightlifeOutlinedIcon,
    bg: "bg-purple-600",
    color: "text-black",
  },
  {
    slug: "womens-dresses",
    name: "Womens Dresses",
    url: "https://dummyjson.com/products/category/womens-dresses",
    icon: NightlifeOutlinedIcon,
    bg: "bg-pink-700",
    color: "text-white",
  },
  {
    slug: "womens-jewellery",
    name: "Womens Jewellery",
    url: "https://dummyjson.com/products/category/womens-jewellery",
    icon: NightlifeOutlinedIcon,
    bg: "bg-yellow-700",
    color: "text-black",
  },
  {
    slug: "womens-shoes",
    name: "Womens Shoes",
    url: "https://dummyjson.com/products/category/womens-shoes",
    icon: NightlifeOutlinedIcon,
    bg: "bg-amber-500",
    color: "text-black",
  },
  {
    slug: "womens-watches",
    name: "Womens Watches",
    url: "https://dummyjson.com/products/category/womens-watches",
    icon: NightlifeOutlinedIcon,
    bg: "bg-purple-500",
    color: "text-white",
  },
];
